### ISSUE TITLE
Misc. tweaks may be in order: screenshots, tables, etc

### ISSUE THREAD

**Issue by chalin** [naomiblack/angulardart.org#14]
- Chap. 1 screenshots should have shadow boarders like in Chap. 2 because they are white on white.
- Tables are still a bit difficult to read without internal boarders (index.html, Chap.4).
- In some cases ellipses is a single character and other three. Maybe be consistent. (Actually, I wasn't sure if the single character ellipse would case problems so I figured I would bring up the potential issue.)

**Comment by brianhall** [comment]
Hello @chalin, thanks for the feedback. I have fixed the screenshots and table style with 8aa172bd6c4cdef5c9a826cf12b40cc12d8f5dcf, but am not totally clear about the ellipses issue. Would you mind providing an example of each way that we are representing the ellipses (and the location of each instance) so that I can make them consistent? Thanks!

**Comment by chalin** [comment]
Sure, here are some examples:
- Ellipses as a single character appears inside the `<div recipe-book>` code snippet of Chapter 2 (the code snippet is just before the "Angular features" section).
- Ellipses as three characters appears, e.g., in the first code snippet (of a `<span>` element) of Chapter 4.

**Comment by kwalrath** [comment]
I've usually tried to use three characters, since I'm not sure the ellipsis character would work everywhere.

**Comment by chalin** [comment]
That was my feeling too. Note that there are some occurrences of the single character ellipses in the main prose too. E.g., again, towards the top of Chapter 4 there is "View it in Dart Editor by using File > Open Existing Folder… to open".

**Comment by brianhall** [comment]
Thanks for the quick feedback. I've done a tutorial-wide search and replace for the single character, and replaced each instance with the separate characters in this commit: 3d6196c0cf173ca096ba0a391c59809df9e50fd9

**Comment by kwalrath** [comment]
Thanks, Brian.
