### ISSUE TITLE
[tutorial] pretty printing is not working and footer nav looks squished

### ISSUE THREAD

**Issue by chalin** [naomiblack/angulardart.org#6]
Not sure if these issues are already on someone's todo list, but just in case. 

(1) When I browse the tutorial, pretty printing is not working for me; e.g. , from Chapter 1

![image](https://f.cloud.github.com/assets/4140793/2056680/258e62fa-8ae8-11e3-8de9-80bd3afe7fa1.png)

Should `prettify.min.js` be included, in the various chapters (and `prettyPrint()` be triggered somehow)?

(2) This is the footer nav looks like to me:

![image](https://f.cloud.github.com/assets/4140793/2056701/4b509b24-8ae9-11e3-9ba2-14eac0918f81.png)

regardless of how wide the window is.

**Comment by brianhall** [comment]
Fixed with 7a2c0b4aa12f87d3f469c737b1cee9ce7c6d0690
